### ISSUE TITLE
umbrella apps and confog

### ISSUE THREAD

**Issue by MeterSoft** [schnittchen/onartsipac#31]
I have umbrella app. For example app_1 app_2 and app_3.
app_1 and app_2 is main apps.
i added config for Rollbar to app_1 in config/prod.exs
also added dep rollbar to app_1

set :distillery_release, "#{fetch(:application)}"
and deploy 
cap app_1 deploy. It works well
but when i start deploy my app_2
cap app_1 deploy. It works well
my app is crash because can not find module Rollbar.
It looks like that itparse all prod.exs files to one. Why? How i can fix this?

**Comment by MeterSoft** [comment]
It is possible go to umbrella app path before run command
`mix release --env=prod --name=umbrella_app`

like `cd apps/umbrella_app` and then run all comands

**Comment by schnittchen** [comment]
I am not sure I understand you correctly. Do you need to deploy different releases with each a different set of applications?

Having `mix release` called with varying options is supported, see https://github.com/schnittchen/carafe/blob/master/lib/capistrano/tasks/buildhost.rake#L98.

A note about configuration in umbrella apps: there is no such thing as separate app configs, really. The top level `config.exs` imports all config files from all apps with the line `import_config "../apps/*/config/config.exs"`. This is sensible because erlang releases only have one set of configuration.
I hope this helps to understand how configuration in an umbrella can and cannot be used!

**Comment by schnittchen** [comment]
@bitwalker's explanation https://github.com/bitwalker/distillery/issues/396#issuecomment-363906611 about umbrella configs is even a bit better.

**Comment by MeterSoft** [comment]
i override you task and now my deploy use only one umbrella app to release. I added
`set :release_path, "/home/property/three_taps/#{fetch(:application)}/build/apps/#{fetch(:application)}"`
and changed task to execute from this folder
`
task "buildhost:mix:deps.get" do
  on build_host do |host|
    within release_path do
      with mix_env: mix_env do
        execute :mix, "local.hex", "--force"
        execute :mix, "local.rebar", "--force"
        execute :mix, "deps.get"
      end
    end
  end
end
`

`
task "buildhost:mix:compile" do
  on build_host do |host|
    within release_path do
      with mix_env: mix_env do
        execute :mix, "compile"
      end
    end
  end
end
`

So now it use only own setting and deps

**Comment by schnittchen** [comment]
I still have not really understood how your releases are different with regards to configuration of your umbrella applications. Maybe an umbrella is not the right tool for what you need?

Anyway, I'm happy that it looks like you found a way around your problem.
